// import 'package:flutter/material.dart';
// import 'package:http/http.dart';
// import 'dart:async';
// import 'dart:convert';
// class _profileState extends State<Profile> {
//   final List _id = [];/
//   List<Autogenerated>? welcome;
//   var idUrl = 'https://run.mocky.io/v3/bdcdffd7-df4c-4645-8290-d451ea6fe98a';
//   Future<List> getprofile() async {
//     http.Response res = await http.get(Uri.parse(idUrl));
//     try {
//       if (res.statusCode == 200) {
//         List<dynamic> pro = json.decode(res.body);
//         print('h');
//         return pro.map((e) => Autogenerated.fromJson(e)).toList();
//       } else {
//         throw "Unable to retrieve posts.";
//       }
//     } catch (e) {
//       print(e);
//       print('hd');
//       return [];
//     }
//   }

//   @override
//   void initState() {
//     getprofile().then((value) {
//       setState(() {
//         _id.addAll(value);
//       });
//     });
//     super.initState();
//     SplashScreen();
//   }